import Header from "@/components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="font-text bg-[#1E2327] text-white transition-all">
        <Header />
        {children}
      </body>
    </html>
  );
}
